### ISSUE TITLE
Rust module seems incompatible with systemd (filesystem)

### ISSUE THREAD

**Issue by PrimaElectro** [Azure/meta-iotedge#17]
i'm compiling a yocto project  (sumo based) with systemd option. Adding the Rust layer, Iget the following error:

> ERROR: cargo-native-0.25.0-r0 do_compile: Function failed: do_compile
> 
>   ERROR: Task (virtual:native:/home/user/pe-yocto-4.1/build/../git/meta-rust/recipes-devtools/cargo/cargo_0.25.0.bb:do_compile)

probably this module is not compatible with the filesystem (systemd), has anyone had the same problem?

this is my bblayers.conf :

> POKY_BBLAYERS_CONF_VERSION = "2"
> 
> BBPATH = "${TOPDIR}"
> SRCDIR = "${TOPDIR}/../git"
> 
> BBLAYERS ?= " \
>   ${SRCDIR}/meta-freescale \
>   ${SRCDIR}/yocto-poky/meta \
>   ${SRCDIR}/yocto-poky/meta-poky \
>   ${SRCDIR}/yocto-poky/meta-yocto-bsp \
>   ${SRCDIR}/yocto-meta-openembedded/meta-gnome \
>   ${SRCDIR}/yocto-meta-openembedded/meta-oe \
>   ${SRCDIR}/yocto-meta-openembedded/meta-python \
>   ${SRCDIR}/yocto-meta-openembedded/meta-networking \
>   ${SRCDIR}/yocto-meta-openembedded/meta-multimedia \
>   ${SRCDIR}/meta-rust \
>   ${SRCDIR}/meta-virtualization \
>   ${SRCDIR}/meta-iotedge \
> "
> 
> BBLAYERS_NON_REMOVABLE ?= " \
>   ${SRCDIR}/yocto-poky/meta \
>   ${SRCDIR}/yocto-poky/meta-poky \
>   "

**Comment by myagley** [comment]
Thanks for the issue report. Systemd is compatible with these layers. The sumo images we run all use `systemd` as init.

It looks like `cargo` is failing to build. Is it possible to get the logs for this build step. It also looks like this version of cargo is fairly old. I would try pulling down the latest commits for `meta-rust`. Note, that we require `meta-rust` to use the `master` branch, not the `sumo` branch.

**Comment by geoffrey-vl** [comment]
It's been nearly one year, is this still relevant?

**Comment by micahl** [comment]
Closing.  Stale issue.
