### ISSUE TITLE
Post install iotedge permissions needed

### ISSUE THREAD

**Issue by philsop** [Azure/meta-iotedge#23]
**Description:** Iot edge lacks permissions to read it's own config and /var/lib directory post install.

**To Reproduce Steps to reproduce the behavior:**

Add meta-iotedge layer to yocto build
Build image
Flash image to sd card
Boot from sd card, then provide connection string to /etc/iotedge/config.yaml
**Expected behavior:** iotedge should simply start working and pulling images

**Logs If applicable, add logs to help explain your problem.**

**Build System (please complete the following information):**

OS: Linux x64
Version 3.12.49-11

**Target System (please complete the following information):** 

OS: yocto rocko
Version rocko
Running on variscite VAR-SOM-6UL (imx6ul-var-dart)

To fix this I had to run the following commands:
$ chown -R iotedge /etc/iotedge
$ chown -R iotedge /var/lib/iotedge
There's also a problem with the hostname property in the config, it's not set properly and you have to set it manually. I feel that all these should be taken care of in post install scripts.

**Comment by micahl** [comment]
Seemingly stale issue.  Closing.
