### ISSUE TITLE
While adding layer of virtualization, bitbake is showing core layer incompatible error

### ISSUE THREAD

**Issue by philipcaffeine** [Azure/meta-iotedge#51]
**Describe the bug**
While adding layer of virtualization, bitbake is showing core layer incompatible error for ST Disco board, STM32MP157.  Will meta-iotedge supporting dunfell build? 

**To Reproduce**

1. cd $HOME/STM32MPU_workspace/Distribution-Package 
2. git clone git://github.com/meta-rust/meta-rust.git 
3. git clone -b thud git://git.yoctoproject.org/meta-virtualization
4. git clone git://github.com/openembedded/openembedded-core.git
5. git clone -b thud https://github.com/Azure/meta-iotedge.git 
6. cd meta-rust
7. git checkout c5ff05d1e99c1e80844c1673456e2368499918c7 -b INT_AZURE
8. cd $HOME/STM32MPU_workspace/Distribution-Package/openstlinux-4.19-thud-mp1-19-10-09 
9. DISTRO=openstlinux-weston MACHINE=stm32mp1 source layers/meta-st/scripts/envsetup.sh
10. bitbake-layers add-layer $HOME/STM32MPU_workspace/Distribution-Package/meta-rust/ 
11. bitbake-layers add-layer $HOME/STM32MPU_workspace/Distribution-Package/meta-virtualization/ 
12. bitbake-layers add-layer $HOME/STM32MPU_workspace/Distribution-Package/meta-iotedge/

**Expected behavior**
Expected to bitbake add layers without error before build the final image

**Logs**

--- Starting bitbake server pid 26308 at 2020-11-16 15:48:25.154239 ---
ERROR: Layer virtualization-layer is not compatible with the core layer which only supports these series: dunfell (layer is compatible with thud sumo)

ERROR: Layer virtualization-layer is not compatible with the core layer which only supports these series: dunfell (layer is compatible with thud sumo)

ERROR: Layer virtualization-layer is not compatible with the core layer which only supports these series: dunfell (layer is compatible with thud sumo)

**Build System (please complete the following information):**
 - OS: [Ubuntu]  
 - Version [18.04]

**Target System (please complete the following information):**
 - OS: [openstlinux-5.4-dunfell-mp1-20-11-12]
 - Version [5.4-dunfell-mp1-20-11-12]

**Additional context**

**Comment by micahl** [comment]
A branch for dunfell has been [available since Sep/Oct 2020](https://github.com/Azure/meta-iotedge/commit/1b3765efe33f053e7bffd7b107bb1b1928ccb6a3).  Closing this old issue.
