### ISSUE TITLE
Add an information to run the "check-config" script by "moby"

### ISSUE THREAD

**Issue by SimonSimCity** [Azure/meta-iotedge#53]
Since I used now quite some time to nail down some errors, I think it's time to add a notification somewhere of the script provided by `moby` by which you can check several kernel settings if they are configured "containerfriendly":

```sh
curl -sSL https://raw.githubusercontent.com/moby/moby/master/contrib/check-config.sh -o check-config.sh
chmod +x check-config.sh
./check-config.sh
```

**Comment by micahl** [comment]
@SimonSimCity, please also take a look at the [platform compatibility script for IoT Edge](https://github.com/Azure/iotedge/blob/main/platform-validation/docs/aziot-compatibility-get-started.md).  We're still refining it, so any feedback would be appreciated.
