### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by vish74** [Azure/meta-iotedge#62]
Is there any documentation or README for creating cargo based recipes? (auto generate)
I would like to update iotedge-daemon and iotedge-cli to 1.1.1 for my local build, but I am not familiar with cargo-bitbake.

**Comment by willfrazer** [comment]
I second this particularly as the latest 1.2 release is very different to previous versions.

Please help by documenting this process (or providing a later recipe for the latest version).

**Comment by micahl** [comment]
> providing a later recipe for the latest version

@willfrazer see https://github.com/Azure/meta-iotedge/pull/90.
