### ISSUE TITLE
Can't build warrior branch

### ISSUE THREAD

**Issue by kriive** [Azure/meta-iotedge#71]
**Describe the bug**
Can't build with warrior branch.

**To Reproduce**
1. Checkout meta-rust in master
2. Checkout meta-iotedge in warrior branch
3. Build
4. See error (include security, due to new syntax)

**Expected behavior**
It should build iotedge and iotedged. But it doesn't.

I tried checking out meta-rust at 1.47, still some errors (url libs 1.7.0-related). 
Tried meta-rust 1.39, other compilation errors.

**Logs**
If applicable, add logs to help explain your problem.

**Build System (please complete the following information):**
 - OS: CROPS

**Target System (please complete the following information):**
 - OS: yocto warrior
 - Version 2.7.3

**Additional context**
Can't build. Which version should I be using of either meta-rust/meta-iotedge...?

**Comment by kriive** [comment]
Managed to build warrior branch with commit ```0d03c206c3d56c6dd6d8bb59bb5f4f8e32ea3f95``` in meta-rust

**Comment by kriive** [comment]
It would be nice if we had newer iotedge binaries in warrior also

**Comment by darobs** [comment]
It would be - We are currently focused on making sure our meta-iotedge project in the dunfell branch has the latest 1.1 iotedge binaries.

**Comment by micahl** [comment]
Closing.  The latest 1.4 recipes are in the Dunfell branch.  We're not planning to port them to older branches, but are open to reviewing a pull request.
