### ISSUE TITLE
iotedge-cli and iotedge-daemon are preventing from build offline, throwing unable to update error

### ISSUE THREAD

**Issue by Mallikarjun62** [Azure/meta-iotedge#83]
Build Configuration:
BB_VERSION           = "1.44.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-18.04"
TARGET_SYS           = "aarch64-poky-linux"
MACHINE              = "iot-gate-imx8"
DISTRO               = "fsl-imx-xwayland"
DISTRO_VERSION       = "5.4-zeus"
TUNE_FEATURES        = "aarch64"
TARGET_FPU           = ""
meta                 
meta-poky            = "HEAD:cba967414370e195d109353e51510bd829aa86c3"
meta-oe              
meta-multimedia      
meta-python          = "HEAD:9e60d30669a2ad0598e9abf0cd15ee06b523986b"
meta-freescale       = "HEAD:c2a0d924f6200eea1fb1d1b61e7420ea5da2f8fb"
meta-freescale-3rdparty = "HEAD:dbcc686f52c3c84db8cb86aa8973a4e373651b98"
meta-freescale-distro = "HEAD:ca27d12e4964d1336e662bcc60184bbff526c857"
meta-bsp             
meta-sdk             
meta-ml              = "HEAD:c4fe39a37226029044c4a0c2d01b1cb77a9b8d8e"
meta-browser         = "HEAD:5f365ef0f842ba4651efe88787cf9c63bc8b6cb3"
meta-rust            = "HEAD:a012a1027defe28495f06ed522a7a82bdd59a610"
meta-gnome           
meta-networking      
meta-filesystems     = "HEAD:9e60d30669a2ad0598e9abf0cd15ee06b523986b"
meta-qt5             = "HEAD:b8bcf8cb576d072f435a0177375e54424f67d1c9"
meta-python2         = "HEAD:231c3d74cfcf734c3415e86ea8dd97f73ddced9d"
meta-compulab        = "HEAD:f5f8a2198e2bf037e1999653b9149c0622c9a0ec"
meta-desktop         
meta-multimedia      
meta-graphics        
meta-bsp             
meta-utils           = "HEAD:01015e56471b1eac23f9024d8a1225e0be54972d"
meta-bsp-imx8mm      = "HEAD:a78ec1549432bef31eb2ceeb03f7cb4c03891434"
meta-virtualization  = "zeus:7e5219669ff6f8e9c8c33ffd230e95a6b2b025f4"
meta-iotedge         = "zeus:9e2b459177f163aaeeb95d2e3fd3dc6ccfb9da44"

Initialising tasks: 100% |###################################################################################################################################################################| Time: 0:00:02
Sstate summary: Wanted 292 Found 273 Missed 19 Current 1620 (93% match, 99% complete)
NOTE: Executing Tasks
NOTE: Setscene tasks completed
WARNING: linux-firmware-1_20190815-r0 do_fetch: Failed to fetch URL git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git, attempting MIRRORS if available
ERROR: iotedge-cli-1.1.4-r0 do_compile: Execution of '/home/manasa/build-cmdline/tmp/work/aarch64-poky-linux/iotedge-cli/1.1.4-r0/temp/run.do_compile.6658' failed with exit code 101:
warning: unused key `term.progress` in config file `/home/manasa/build-cmdline/tmp/work/aarch64-poky-linux/iotedge-cli/1.1.4-r0/cargo_home/config`
    Updating git repository `https://github.com/Azure/hyperlocal-windows`
error: failed to load source for a dependency on `hyperlocal-windows`

Caused by:
  Unable to update https://github.com/Azure/hyperlocal-windows#2bd432bb

Caused by:
  failed to fetch into /home/manasa/build-cmdline/tmp/work/aarch64-poky-linux/iotedge-cli/1.1.4-r0/cargo_home/git/db/hyperlocal-windows-23da91d031a39873

Caused by:
  invalid version 3 on git_proxy_options; class=Invalid (3)
WARNING: exit code 101 from a shell command.

ERROR: Logfile of failure stored in: /home/manasa/build-cmdline/tmp/work/aarch64-poky-linux/iotedge-cli/1.1.4-r0/temp/log.do_compile.6658
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: cargo = /home/manasa/build-cmdline/tmp/work/aarch64-poky-linux/iotedge-cli/1.1.4-r0/recipe-sysroot-native/usr/bin/cargo
| NOTE: rustc =
| NOTE: cargo build -v --target aarch64-poky-linux --release
| warning: unused key `term.progress` in config file `/home/manasa/build-cmdline/tmp/work/aarch64-poky-linux/iotedge-cli/1.1.4-r0/cargo_home/config`
|     Updating git repository `https://github.com/Azure/hyperlocal-windows`
| error: failed to load source for a dependency on `hyperlocal-windows`
| 
| Caused by:
|   Unable to update https://github.com/Azure/hyperlocal-windows#2bd432bb
| 
| Caused by:
|   failed to fetch into /home/manasa/build-cmdline/tmp/work/aarch64-poky-linux/iotedge-cli/1.1.4-r0/cargo_home/git/db/hyperlocal-windows-23da91d031a39873
| 
| Caused by:
|   invalid version 3 on git_proxy_options; class=Invalid (3)
| WARNING: exit code 101 from a shell command.
| ERROR: Execution of '/home/manasa/build-cmdline/tmp/work/aarch64-poky-linux/iotedge-cli/1.1.4-r0/temp/run.do_compile.6658' failed with exit code 101:
| warning: unused key `term.progress` in config file `/home/manasa/build-cmdline/tmp/work/aarch64-poky-linux/iotedge-cli/1.1.4-r0/cargo_home/config`
|     Updating git repository `https://github.com/Azure/hyperlocal-windows`
| error: failed to load source for a dependency on `hyperlocal-windows`
| 
| Caused by:
|   Unable to update https://github.com/Azure/hyperlocal-windows#2bd432bb
| 
| Caused by:
|   failed to fetch into /home/manasa/build-cmdline/tmp/work/aarch64-poky-linux/iotedge-cli/1.1.4-r0/cargo_home/git/db/hyperlocal-windows-23da91d031a39873
| 
| Caused by:
|   invalid version 3 on git_proxy_options; class=Invalid (3)
| WARNING: exit code 101 from a shell command.
| 
ERROR: Task (/home/manasa/sources/meta-iotedge/recipes-core/iotedge-cli/iotedge-cli_1.1.4.bb:do_compile) failed with exit code '1'
ERROR: iotedge-daemon-1.1.4-r0 do_compile: Execution of '/home/manasa/build-cmdline/tmp/work/aarch64-poky-linux/iotedge-daemon/1.1.4-r0/temp/run.do_compile.6661' failed with exit code 101:
warning: unused key `term.progress` in config file `/home/manasa/build-cmdline/tmp/work/aarch64-poky-linux/iotedge-daemon/1.1.4-r0/cargo_home/config`
    Updating git repository `https://github.com/Azure/hyperlocal-windows`
error: failed to load source for a dependency on `hyperlocal-windows`

Caused by:
  Unable to update https://github.com/Azure/hyperlocal-windows#2bd432bb

Caused by:
  failed to fetch into /home/manasa/build-cmdline/tmp/work/aarch64-poky-linux/iotedge-daemon/1.1.4-r0/cargo_home/git/db/hyperlocal-windows-23da91d031a39873

Caused by:
  invalid version 3 on git_proxy_options; class=Invalid (3)
WARNING: exit code 101 from a shell command.

ERROR: Logfile of failure stored in: /home/manasa/build-cmdline/tmp/work/aarch64-poky-linux/iotedge-daemon/1.1.4-r0/temp/log.do_compile.6661
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: cargo = /home/manasa/build-cmdline/tmp/work/aarch64-poky-linux/iotedge-daemon/1.1.4-r0/recipe-sysroot-native/usr/bin/cargo
| NOTE: rustc =
| NOTE: cargo build -v --target aarch64-poky-linux --release
| warning: unused key `term.progress` in config file `/home/manasa/build-cmdline/tmp/work/aarch64-poky-linux/iotedge-daemon/1.1.4-r0/cargo_home/config`
|     Updating git repository `https://github.com/Azure/hyperlocal-windows`
| error: failed to load source for a dependency on `hyperlocal-windows`
| 
| Caused by:
|   Unable to update https://github.com/Azure/hyperlocal-windows#2bd432bb
| 
| Caused by:
|   failed to fetch into /home/manasa/build-cmdline/tmp/work/aarch64-poky-linux/iotedge-daemon/1.1.4-r0/cargo_home/git/db/hyperlocal-windows-23da91d031a39873
| 
| Caused by:
|   invalid version 3 on git_proxy_options; class=Invalid (3)
| WARNING: exit code 101 from a shell command.
| ERROR: Execution of '/home/manasa/build-cmdline/tmp/work/aarch64-poky-linux/iotedge-daemon/1.1.4-r0/temp/run.do_compile.6661' failed with exit code 101:
| warning: unused key `term.progress` in config file `/home/manasa/build-cmdline/tmp/work/aarch64-poky-linux/iotedge-daemon/1.1.4-r0/cargo_home/config`
|     Updating git repository `https://github.com/Azure/hyperlocal-windows`
| error: failed to load source for a dependency on `hyperlocal-windows`
| 
| Caused by:
|   Unable to update https://github.com/Azure/hyperlocal-windows#2bd432bb
| 
| Caused by:
|   failed to fetch into /home/manasa/build-cmdline/tmp/work/aarch64-poky-linux/iotedge-daemon/1.1.4-r0/cargo_home/git/db/hyperlocal-windows-23da91d031a39873
| 
| Caused by:
|   invalid version 3 on git_proxy_options; class=Invalid (3)
| WARNING: exit code 101 from a shell command.
| 
ERROR: Task (/home/manasa/sources/meta-iotedge/recipes-core/iotedge-daemon/iotedge-daemon_1.1.4.bb:do_compile) failed with exit code '1'

**Comment by micahl** [comment]
The latest recipes for 1.4 are in the Dunfell branch.  Starting with v1.2 IoT Edge does not directly target Windows and therefore doesn't reference those failing repositories in the latest recipes.  Closing this issue.  Please open a new one if an issue exists with the 1.4 recipes.
